/**
 *@Generated by sagacity-quickvo 5.0
 */
package net.cocotea.elysiananime.api.anime.model.po;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import lombok.Data;
import lombok.experimental.Accessors;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author CoCoTea
 * @version 1.0.0 
 */
@Data
@Accessors(chain = true)
@Entity(tableName="ani_opus_tag",comment="作品标签关联表",pk_constraint="PRIMARY")
public class AniOpusTag implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4611686393882064321L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name="id",comment="作品标签关联id",length=3L,type=java.sql.Types.TINYINT,nativeType="TINYINT",nullable=false)
	private BigInteger id;

	@Column(name="tag_id",comment="标签id",length=19L,type=java.sql.Types.BIGINT,nativeType="BIGINT",nullable=false)
	private BigInteger tagId;

	@Column(name="opus_id",comment="作品id",length=19L,type=java.sql.Types.BIGINT,nativeType="BIGINT",nullable=false)
	private BigInteger opusId;

	@Column(name="create_time",comment="关联时间",length=19L,type=java.sql.Types.DATE,nativeType="DATETIME",nullable=true)
	private LocalDateTime createTime;
	/** default constructor */
	public AniOpusTag() {
	}
	
	/** pk constructor */
	public AniOpusTag(BigInteger id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
