/**
 *@Generated by sagacity-quickvo 5.0
 */
package net.cocotea.janime.api.anime.model.po;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import lombok.Data;
import lombok.experimental.Accessors;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author CoCoTea
 * @version 1.0.0 
 */
@Data
@Accessors(chain = true)
@Entity(tableName="ani_opus",comment="作品主表",pk_constraint="PRIMARY")
public class AniOpus implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7665174370014079908L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name="id",comment="作品id",length=19L,type=java.sql.Types.BIGINT,nativeType="BIGINT",nullable=false)
	private BigInteger id;

	@Column(name="name_original",comment="原名",length=100L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String nameOriginal;

	@Column(name="name_cn",comment="中文名",length=100L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String nameCn;

	@Column(name="cover_url",comment="封面地址",length=200L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String coverUrl;

	@Column(name="detail_info_url",comment="详细链接",length=200L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String detailInfoUrl;

	@Column(name="episodes",comment="话数",length=100L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String episodes;

	@Column(name="launch_start",comment="放送开始",length=100L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String launchStart;

	@Column(name="delivery_week",comment="放送星期",length=100L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String deliveryWeek;

	@Column(name="ani_summary",comment="作品简介",length=65535L,type=java.sql.Types.VARCHAR,nativeType="TEXT",nullable=true)
	private String aniSummary;

	@Column(name="has_resource",comment="是否有资源：0否 1是",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nativeType="TINYINT",nullable=true)
	private Integer hasResource;

	@Column(name="rss_url",comment="rss订阅链接",length=900L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String rssUrl;

	@Column(name="rss_status",comment="订阅状态: 0未订阅 1订阅中 2订阅完成",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nativeType="TINYINT",nullable=true)
	private Integer rssStatus;

	@Column(name="rss_level_index",comment="资源标题集数出现的位置（数字匹配）",length=10L,defaultValue="0",type=java.sql.Types.INTEGER,nativeType="INT",nullable=true)
	private Integer rssLevelIndex;

	@Column(name="rss_file_type",comment="要订阅的资源格式",length=10L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String rssFileType;

	@Column(name="rss_only_mark",comment="匹配的唯一标识",length=50L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String rssOnlyMark;

	@Column(name="rss_exclude_res",comment="排除的资源",length=50L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=true)
	private String rssExcludeRes;

	@Column(name="create_time",comment="创建时间",length=19L,type=java.sql.Types.DATE,nativeType="DATETIME",nullable=false)
	private LocalDateTime createTime;

	@Column(name="create_by",comment="创建人",length=19L,type=java.sql.Types.BIGINT,nativeType="BIGINT",nullable=true)
	private BigInteger createBy;

	@Column(name="update_time",comment="更新时间",length=19L,type=java.sql.Types.DATE,nativeType="DATETIME",nullable=false)
	private LocalDateTime updateTime;

	@Column(name="update_by",comment="更新人",length=19L,type=java.sql.Types.BIGINT,nativeType="BIGINT",nullable=true)
	private BigInteger updateBy;

	@Column(name="is_deleted",comment="是否删除",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nativeType="TINYINT",nullable=false)
	private Integer isDeleted;
	/** default constructor */
	public AniOpus() {
	}
	
	/** pk constructor */
	public AniOpus(BigInteger id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
