/**
 *@Generated by sagacity-quickvo 5.0
 */
package net.cocotea.janime.api.anime.model.po;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import lombok.Data;
import lombok.experimental.Accessors;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author CoCoTea
 * @version 1.0.0 
 */
@Data
@Accessors(chain = true)
@Entity(tableName="ani_tag",comment="acg标签表",pk_constraint="PRIMARY")
public class AniTag implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1991691926851254164L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name="id",comment="标签id",length=19L,type=java.sql.Types.BIGINT,nativeType="BIGINT",nullable=false)
	private BigInteger id;

	@Column(name="tag_name",comment="标签名称",length=100L,type=java.sql.Types.VARCHAR,nativeType="VARCHAR",nullable=false)
	private String tagName;

	@Column(name="create_time",comment="创建时间",length=19L,type=java.sql.Types.DATE,nativeType="DATETIME",nullable=false)
	private LocalDateTime createTime;

	@Column(name="create_by",comment="创建人",length=19L,type=java.sql.Types.BIGINT,nativeType="BIGINT",nullable=false)
	private BigInteger createBy;

	@Column(name="update_time",comment="更新时间",length=19L,type=java.sql.Types.DATE,nativeType="DATETIME",nullable=true)
	private LocalDateTime updateTime;

	@Column(name="update_by",comment="更新人",length=19L,type=java.sql.Types.BIGINT,nativeType="BIGINT",nullable=true)
	private BigInteger updateBy;

	@Column(name="is_deleted",comment="是否删除",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nativeType="TINYINT",nullable=false)
	private Integer isDeleted;
	/** default constructor */
	public AniTag() {
	}
	
	/** pk constructor */
	public AniTag(BigInteger id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
